name: BKDocs check suite

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: "*"
    paths: 
      - "**.md"

env:
  IS_TRACE: false

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get Changed Files
        id: getfile
        shell: bash
        run: |
          [[ $IS_TRACE == 'true' ]] && set -x
          set -eu
          if [ $GITHUB_BASE_REF ]; then
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( while IFS= read -r -d '' x; do printf '%q\n' "$x"; done < <( git diff --name-only -z origin/$GITHUB_BASE_REF $GITHUB_SHA ) )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            echo "no BASE REF"
            exit 1
          fi
          echo "${DIFF[@]}" | sort -u
          echo "::set-output name=diff::$( echo "${DIFF[@]}" | sort -u )"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - name: Lint Markdown
        shell: bash
        run: |
          [[ $IS_TRACE == 'true' ]] && set -x
          npm i -g lint-md-cli
          lint-md ${{ steps.getfile.outputs.diff }}
