name: Node.js CI

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Plugin and Check
        run: |
          set -ex
          npm i -g lint-md-cli
          # lint-md docs/*
          git diff --diff-filter=d --name-only "${GITHUB_BASE_REF}...${GITHUB_HEAD_REF}"
        shell: bash
