name: BKDocs create release

on:
  release:
    type: [created]
    
jobs:
  Release a Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Project
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          tar czf docs-${GITHUB_REF}.tar.gz ZH
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          url:  ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docs-${GITHUB_REF}.tar.gz
          asset_name: docs-${GITHUB_REF}.tar.gz
          asset_content_type: application/x-gzip
          
