name: BKDocs create release

on:
  push:
    tags: 
      - 'v*'
    
jobs:
  Release_a_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Project
        id: build_project
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          tar czf docs-${GITHUB_REF##*/}.tgz ZH
          echo "::set-output name=release_asset::$( echo docs-${GITHUB_REF##*/}.tgz )"
      - name: Get Upload URL
        id: get_upload_url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -eux
          export UPLOAD_URL=$( curl -s -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/shpdnkti/bkdocs_test/releases/tags/${GITHUB_REF##*/} \
            | python -c 'import json,sys; print json.load(sys.stdin)["upload_url"]' \
            | sed 's/{?name,label}//' )
          echo "::set-output name=upload_url::$( echo ${UPLOAD_URL} )"
      
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: $GITHUB_WORKSPACE/${{ steps.build_project.outputs.release_asset }}
          asset_name: ${{ steps.build_project.outputs.release_asset }}
          asset_content_type: application/x-gzip
          
