# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - "*"

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          path: docs
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install plugin and check
        run: |
          npm i -g lint-md-cli
          pwd
          lint-md *
          
